extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: basic
  otlp/graylog:
    endpoint: graylog:4317
    tls:
      insecure: true
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, otlp/graylog]
    metrics:
      receivers: [otlp]
      exporters: [debug, prometheus]
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger]
